name: 🌐 Deploy Newsletter Web Interface

on:
  push:
    branches: [ main, feature/newsletter-signup ]
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🧪 Run tests
      run: python test.py
      
    - name: 📊 Generate static pages
      run: |
        # Create a simple static version of the signup form
        mkdir -p docs
        python -c "
        from email_manager import EmailManager
        import json
        
        # Initialize with empty subscribers for demo
        manager = EmailManager('subscribers.json')
        stats = manager.get_stats()
        
        # Create a simple HTML page
        html = f'''
        <!DOCTYPE html>
        <html lang=\"en\">
        <head>
            <meta charset=\"UTF-8\">
            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
            <title>🛰️ Aerospace Newsletter Signup</title>
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    margin: 0;
                    padding: 20px;
                    min-height: 100vh;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }}
                .container {{
                    background: white;
                    border-radius: 12px;
                    padding: 40px;
                    max-width: 500px;
                    width: 100%;
                    text-align: center;
                    box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                }}
                .header h1 {{
                    font-size: 2.5rem;
                    color: #2d3748;
                    margin-bottom: 10px;
                }}
                .stats {{
                    background: #f7fafc;
                    border-radius: 8px;
                    padding: 20px;
                    margin: 20px 0;
                }}
                .form-group {{
                    margin: 20px 0;
                    text-align: left;
                }}
                .form-group input {{
                    width: 100%;
                    padding: 12px 16px;
                    border: 2px solid #e2e8f0;
                    border-radius: 8px;
                    font-size: 16px;
                    box-sizing: border-box;
                }}
                .btn {{
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    border: none;
                    padding: 12px 30px;
                    border-radius: 25px;
                    font-size: 16px;
                    font-weight: 600;
                    cursor: pointer;
                    width: 100%;
                }}
                .message {{
                    padding: 12px 16px;
                    border-radius: 8px;
                    margin: 20px 0;
                }}
                .success {{
                    background: #f0fff4;
                    color: #22543d;
                    border: 1px solid #9ae6b4;
                }}
                .error {{
                    background: #fed7d7;
                    color: #742a2a;
                    border: 1px solid #feb2b2;
                }}
            </style>
        </head>
        <body>
            <div class=\"container\">
                <div class=\"header\">
                    <h1>🛰️ Aerospace Newsletter</h1>
                    <p>Stay updated with the latest aerospace and defense news</p>
                </div>
                
                <div class=\"stats\">
                    <h3>📊 Newsletter Stats</h3>
                    <p><strong>{stats['active_subscribers']}</strong> active subscribers</p>
                    <p>Delivered twice weekly (Tuesday & Friday)</p>
                </div>
                
                <div id=\"message\"></div>
                
                <form id=\"signupForm\">
                    <div class=\"form-group\">
                        <label for=\"email\">Email Address *</label>
                        <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"your@email.com\">
                    </div>
                    
                    <div class=\"form-group\">
                        <label for=\"name\">Name (Optional)</label>
                        <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Your Name\">
                    </div>
                    
                    <button type=\"submit\" class=\"btn\">Subscribe to Newsletter</button>
                </form>
                
                <div style=\"margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 0.9rem;\">
                    <p>Powered by GitHub Actions • <a href=\"#\" onclick=\"alert('Contact admin to unsubscribe')\">Unsubscribe</a></p>
                </div>
            </div>
            
            <script>
                document.getElementById('signupForm').addEventListener('submit', function(e) {{
                    e.preventDefault();
                    
                    const email = document.getElementById('email').value;
                    const name = document.getElementById('name').value;
                    const messageDiv = document.getElementById('message');
                    
                    // Simple validation
                    if (!email) {{
                        messageDiv.innerHTML = '<div class=\"message error\">Email is required</div>';
                        return;
                    }}
                    
                    // For demo purposes, just show success message
                    messageDiv.innerHTML = '<div class=\"message success\">Thank you for subscribing! Please contact the admin to complete your subscription.</div>';
                    document.getElementById('signupForm').reset();
                }});
            </script>
        </body>
        </html>
        '''
        
        with open('docs/index.html', 'w') as f:
            f.write(html)
        "
        
    - name: 📤 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
